// *Standardization notes*
//phases of therapy or phases of rehabilitation
// exergame-based rehabilitation or exergame-based therapy 
//Agency is viewed as an emergent and relational capacity enacted through sociotechnical intra-actions among humans and nonhumans @Frauenberger2019
//This necessitates a reframing of how systems are designed to share agency between humans and systems in rehabilitation settings. 

= Introduction <introduction>
Over the decades, studies have shown how exergames for rehabilitation that promote physical activity and cognitive engagement through gamified tasks, are more effective than traditional rehabilitation due to higher sense of engagement and motivation @Shah2022 @Maier2019 @Allegue2022 @ohyou2010 @Maggio2025. Various processes in exergame-based rehabilitation are also progressively being automated either partially or fully to support precision medicine while reducing therapists' workload @TurmoVidal2025 @Yu2026 @Figueiredo2025eXtendedReality. Subsequently, AI systems are increasingly enacting agency through practices they co-perform with humans, influencing clinical decisions through algorithmic logic and historical data @AttohMensah2025. Agency, can be defined as the capacity to shape social practices and outcomes through situated performances and relational intra-actions among humans and non-humans @Frauenberger2019 @Barad2007. On this view, neither therapist nor AI system are passive actors, but rather active co-performing decision-makers that continuously negotiate roles and responsibility across the rehabilitation process @Frauenberger2019 @Kuijer2018 @GiaccardiRedstrom2020. From this perspective, it is important to understand how to balance the sense of agency between the therapist and the AI-supported system as rehabilitation environments become more hybrid. This is especially critical within rehabilitation where therapists' autonomy and meaningful work should not be undermined or substituted as therapists' situated assessment and support is crucial for patient outcomes @Yu2026.

Despite this, therapists' sense of agency in relation to AI-supported exergame-based rehabilitation systems is generally underexplored and not concrete. What has been discussed are how various factors such as level of automation and increased cognitive workload reduce the sense of agency, and for future research to maintain the human sense of agency in relation to AI systems @Zanatto2021 @Legaspi2024. However, these discussions remain largely theoretical and are rarely examined within the context of AI-supported exergame-based rehabilitation systems specifically. Additionally, existing systems on exergame-based rehabilitation currently mainly provide therapists dashboards, data documentation, adaptive session planning, and task manipulation, while excluding the general rehabilitation process @Figueiredo2025HybridControl @GagnonRoy2025 @Eckert2023 @Ferreira2022. They provide a fixed agency configuration but do not discuss how this distribution of agency might need to change, and how the boundary could be drawn across the main phases of rehabilitation: Assessment & Goal-setting, Session Planning, Rehabilitation Session, and Post-Session Evaluation (See @section:contextualinquiry). Moreover, they also do not discuss therapists' reasoning on the sense of agency in relation to an AI-supported system.

This is important to address as therapists roles could become diminished through reduced sense of agency risking a potential role shift from active decision-makers to passive supervisors. With the aim of addressing this gap and provide design implications, this study explored how therapists reason about their agency in relation to an AI-supported system for exergame-based rehabilitation, and how the agency could be shared between the therapist and the system to maintain it. To do so, a participatory Research through Design (RtD) approach was applied through two main methods: (1) a contextual inquiry conducted through a case study (Brain Stimulation) including interviews and an observation, and (2) individual participatory speculative co-design sessions. These methods were used to first ground the studies in an existing exergame-based rehabilitation setting, subsequently enabling exploration of potential futures and agency concerns in AI-supported rehabilitation systems. To properly achieve the objectives of this study, the following research questions were asked: 

*RQ1:* How do therapists   reason about their sense of agency in relation to a human-AI system for exergame-based rehabilitation?

*RQ2:* How do therapists' preferences for agency distribution vary in relation to an AI system across the main phases of exergame-based rehabilitation?
