// *Standardization notes*
//phases of therapy or phases of rehabilitation
// exergame-based rehabilitation or exergame-based therapy 
//Agency is viewed as an emergent and relational capacity enacted through sociotechnical intra-actions among humans and nonhumans @Frauenberger2019
//This necessitates a reframing of how systems are designed to share agency between humans and systems in rehabilitation settings. 

= Introduction
Over the decades, studies have shown how exergames for rehabilitation is more effective than traditional therapy due to higher sense of engagement and motivation @Shah2022 @Maier2019 @Allegue2022. Various *processes* in exergame-based rehabilitation are also progressively being automated either partially or fully to support precision medicine while reducing therapists workload @Howard2016 @Legaspi2024 @Figueiredo2025eXtendedReality. Subsequently, AI systems are increasingly enacting agency through practices they co-perform with humans and influencing clinical decisions enabled through algorithmic logic and historical data @Jones2023. Agency can be defined as the capacity to shape social practices and outcomes through situated performances and relational intra-actions among humans, technologies, data, and infrastructures @Frauenberger2019. This means that neither therapist nor AI system are passive actors in a rehabilitation system but active decision-makers that continuously negotiate roles and responsibility across rehabilitation @Frauenberger2019 @Kuijer2018 @GiaccardiRedstrom2020. From this perspective, it is important to understand how to balance the sense of agency between the therapist and the system as rehabilitation environments become more hybrid. This is especially critical within rehabilitation where therapists autonomy and work should not be undermined or substituted @TurmoVidal2025 @Yu2026. 

Despite this, therapists sense of agency in relation to AI-supported exergame-based rehabilitation systems is generally underexplored and not concrete. What has been discussed are how various factors such as level of automation and increased cognitive workload reduce the sense of agency, as well as how balanced automation can maintain the sense of agency @Howard2016 @Legaspi2024. However, these discussions remain largely theoretical and are rarely examined within the context of AI-supported exergame-based rehabilitation systems specifically. Additionally, existing systems on exergame-based rehabilitation currently mainly provide therapists dashboards, data documentation, adaptive session planning, and task manipulation, while excluding the general therapeutic process @Figueiredo2025HybridControl @GagnonRoy2025 @Eckert2023 @Ferreira2022. Moreover, they also do not discuss therapists sense of agency in relation to the AI-supported system throughout the therapeutic process.

Evidently, the existing systems in research do not address the sense of therapist agency or discuss therapists' agency in relation to the AI-supported system across the therapeutic process. As a result, therapists could risk *diminishment* of their roles by becoming positioned primarily as passive supervisors of system rather than as active actors throughout the therapeutic process. With the aim of addressing this gap and provide design implications, we _explored_ how therapists reason about their agency in relation to an AI-supported computational system for exergame-based rehabilitation and how the agency should be shared between the therapist and the system. To do so, a participatory Research through Design (RtD) approach was applied through two main methods: (1) a contextual inquiry conducted through a case study (Brain Stimulation) including interviews and observation, and (2) individual participatory speculative co-design sessions. These methods were used to first ground the studies in an existing exergame-based rehabilitation setting, subsequently enabling exploration of potential futures and agency concerns in AI-supported rehabilitation systems. To properly achieve the objectives of this study, the following research questions were asked: 

*RQ1:* How do therapists reason about their agency in relation to a human-AI system for exergame-based rehabilitation therapy?

*RQ2:* How do therapists' preferences for agency distribution between themselves and a system (AI) vary across the main phases of exergame-based rehabilitation therapy (i.e. therapy planning & goal-setting, session planning, rehabilitation session, and post-session evaluation)?

