
= Background
This section presents relevant research and frameworks to establish an overview of research on therapist interfaces for rehabilitation through exergames. The chapter covers the following areas: (1) Exergames in Rehabilitation, (2) Therapist Interfaces for Exergame-Based Therapy, and (3) More-than-Human Design.


== Exergames in Rehabilitation

Exergames, a fusion of "exercise" and "video games", are video games that promote physical activity and cognitive engagement through gamified tasks (Oh & Yang, 2010). Although not exclusively, they are often classified under a broader category "Serious Games", which refers to digital games designed primarily for purposes beyond entertainments, such as education, training, and health interventions (Maggio, 2025). The researches also differentiate between commercial off-the-shelf systems and custom systems used for rehabilitation purposes (Allegue et al.,2022). The meta-analyses show exergames systems specifically designed for rehabilitation tend to be more effective than conventional therapy, whereas re-purposed commercial off-the-shelf systems often yield mixed or neutral results, in part because their interaction mechanics and feedback are not tightly aligned with therapeutic goals (Maier et al. 2019). Exergames have shown to support neuroplasticity by enabling high repetition and high intensity task-oriented activities that are challenging enough but not frustrating resulting in increased motivation and engagement (Maier et al., 2019; Allegue et al.,2022; @shah2022). 

A wide range of technologies have been explored to implement exergames for rehabilitation. Non-immersive systems based on Xbox Kinect, Nintendo Wii, PlayStation, Robot-assisted serious games, or similar motion-sensing consoles are widely studied and have shown be be clinically provide effective rehabilitation compared to conventional therapy (Cheok et al., 2015; Santos et al., 2025, Doumas et al., 2025). Similarly, XR-based exergames, which are more immersive in nature, have been used for motor and cognitive rehabilitation after stroke and other neurological conditions, with studies reporting improvements in motor functions, spatial attention, and improved engagement compared to conventional exercises (@fordell2016 @faria2016 ). These studies demonstrate that exergames can be implemented and are being explored in varied technologies across different rehabilitation settings.

Beside providing a gamified exercise and its effectiveness in clinical treatment, exergames can also viewed as interactive systems that generate performance data which can be used to monitor progress and support clinical-decision making. Exergames inherently generate fine-grained performance data (like reaction times, errors, speed) that can be used to adapt game logics in real-time or to monitor progress and support clinical decision-making process across sessions (Ismail et al., 2021). It aids how interfaces, algorithms and workflows can be designed to support personalized rehabilitation alongside providing gamified exercise experience (Mensah et al., 2025). Exergames thus have higher potential of accurately providing and utilizing data-centric monitoring during therapy sessions and create adaptable and fun experiences to fit individual needs allowing patients to participate in interactive and adaptive exercises @rahin2025. One way that has been done is through AI and Machine learning approaches as they have the ability to enable precision medicine by analyzing sensors, game data and performance data to recommend or automatically adjust therapy parameters such as task type, difficulty, movement or session length (Mensah et al,. 2025). However, treating personalization as a purely technical optimisation and user experience problem would be short-sighted without considering patient preferences, motivational factors and meaningful therapeutic goals. 

// talk about patient-therapist relationship // Fix this
These subjective information like patient preferences and feedback, patient motivation, physical and psychological state, and therapists' own work and life experience were among the factors that played crucial role, as well as prioritized, in clinical reasoning of physiotherapists besides just objective data (both motor and physiological). This clinical reasoning helped them set patient goals, decide of treatment plan and adjust rehabilitation sessions (Molle et al., 2025; Holdar et al., 2013). However, novice therapists relied more on informative but objective factors for clinical decision-making compared to experienced therapists, who considered both subjective and objective data to provide personalised rehabilitation (Holdar et al., 2013). This highlights the need to either incorporate or consider subjective data when developing technology for therapeutic process, suggesting therapists should be in the loop instead of adopting full automation (Molle et al., 2025). 

== Therapist Interfaces for Exergame-Based Therapy
Various therapist interfaces for personalized rehabilitation through exergames have been developed, although they do not account for the entirety of the therapy process as they mainly focus on data documentation and/or session planning and task manipulation. One therapist interface for Village Druid VR, a therapy game used for rehabilitation was prototyped along through 2 co-design sessions with 2 therapists each. The lo-fi and hi-fi prototypes focused on patient data documentation for monitoring and progress evaluation as well as some simpler personalization session parameters which were not clearly defined (Ferreira et al., 2022). Similarly, Duval et al. (2022) redesigned an already existing conventional VR game, Spellcasters, through co-design sessions with 14 medical professionals (PT's & OT's). The re-purposed version of Spellcasters focused again solely on data documentation deemed valuable by the medical professionals, and task management through custom rehabilitative gestures to adjust relevant variables including scale, shape, direction and depth.

Another more elaborative study developed a set of collaborative VR serious games, 4 in total, both for upper-limb physical rehabilitation and cognitive rehabilitation of stroke survivors. Again, their framework ADAPT (Adaptive Dynamics for Activity-based Personalized Therapy) only focused on personalized session planning and some game task parameters. For the session planning, therapists could adjust the number of participants, the selection and sequencing of games, session durations and individualized goals. For game task parameters, the therapist could adjust level of difficulty and more detailed adjustments in complexity such as the number and type of objects or puzzle pieces, and in-game payment processes (Figueiredo et al., 2025). 

One study in particular fully isolated game task adjustment in the form of difficulty parameters only. Difficulty in classification in levels were found to lead to longer playtime with more fun and higher performance when compared to high-commitment game parameter goals in terms of goal and time (Eckert et al., 2023). Gagnon-Roy et al. (2024) on the other hand co-developed COOK, a cognitive assistance system together with occupational therapists to help patients regain the ability to prepare meals. Although not an exergame, the patient still has a personalized interface with step-by-step instructions to follow where breaks, reminders and recipe-steps are all pre-configured by the therapist. 

Indisputably, with one exception, previous research does not account for how to share the agency between the therapist and the system. Figueiredo et al. (2025), the exception, highlight in their study that 7 out of 10 participants preferred a hybrid mode combining both automated and manual adjustments, however focused on task personalization only as well. Furthermore, while data documentation does improve evaluation and decision-making and personalized therapy and decision-making, ultimately improving patient care (Tadas et al., 2023; Dawdling et al., 2015 ), the current systems still remain very fragmented as they lack a holistic view of all the main phases in the therapeutic process. The Occupational Intervention Process model includes (1) Evaluation and Goal-Setting Phase, (2) Intervention Phase, (3) Reevaluation Phase (Hinojosa et al., 2017). Physiotherapy largely uses the same basic structure and is often referred to as the "rehab cycle" or "SOAP" which also includes (1) Assessment and goal setting, (2) intervention and (3) re-evaluation (Negrini, 2019; Physiopedia, n.d.; Physiofirstt; 2023). 

// Need to connect to below 
//Existing therapists interfaces treat control as a matter of available parameters and .... focusing on documentation and parameter manipulation while leaving other phases of the therapeutic process. These systems are also fragmented  across different platforms for assessment, therapy, and journaling. It is not sufficient to look at only adjustable parameters or dashboard features, and look 

== More-than-Human 

While prior work on therapist interfaces has primarily examined how individual tools support documentation, session planning, and exergame parameter controls, there is a need to look beyond single applications or interfaces. Recent HCI discussions of post-interaction or "fourth wave" present that designers must understand the shifting paradigm of human-computer relations including how agency and responsibility are distributed between people and computational systems (Mensah, 2025). More-than-human design came about as a response to the limitation of human-centered design in addressing complex socio-technical and ecological challenges (Giacardi & Redström, 2020). In a world where it is no longer exclusively humans that act, design, make use, and change, more-than-human design offers a theoretical lens for understanding rehabilitation exergames as an integrated collection of humans (therapists and patients) and non-humans (such as exergame software, algorithms, data representations, sensors, infrastructure), the agency of which are continuously negotiated (Giacardi & Redström, 2020). As these system become more data-driven, healthcare decisions are increasingly influenced by algorithmic logic and historical data apart from just therapist reasoning (source?). This means, in rehabilitation exergames context, the therapy outcomes are shaped not only by therapists' decisions and patients' performance, but also by how algorithms classify performance, how data is presented, what data is shown or hidden, what technology is used, and even institutional constraints. This reiterates the fact that design in therapeutic scenarios are less about optimizing interfaces of users and more about configuring relationships and agencies among multiple human and nonhuman actors over time. 

//https://ieeexplore.ieee.org/document/10972866 this paper provides tech requirements but fail to consider more-than-human approach

In HCI, agency is presented as the sense of the subjective experience of being in control of actions and their effects in the world, and not only a matter of who executes a task.This sense of agency can be affected by factors such as timing, predictability, and level or form of automation (Legaspi et al, 2024; Limerick, 2014). Experimental studies indicate that higher level of automation and increased mental workload are associated with reduced sense of agency, whereas thoughtfully designed hybrid interactions can maintain a stronger feeling of control even when systems act on user's behalf (Howard et. al, 2016; Legaspi et al, 2024). These findings are particularly relevant in clinical contexts where therapists must be able to stand by decisions, both ethically and legally, even when those clinical decisions are mediated by automated systems. These new developments are often discussed using the notions of human-in-the-loop (HITL), and human-on-the-loop (HOTL). In HITL, humans are embedded in the control loop and must initiate, approve or adjust system decisions before they are executed or can move forward in the workflow. For example, when a therapists manually approves the selects exergames and its parameters or when a therapists manually checks and approves the exergames suggested by a recommendation system. In HOTL, the system operates autonomously while human monitors and intervene when required. For example, when an exergame continuously adjusts game parameters based on patient performance or biofeedback while therapist supervises through their own interface (Lazaros et al., 2026) // maybe find more foundational source but this good for discussion).

Classic LoA taxonomies present how functions are divided between human and machine. These frameworks are tools to understand implications and challenges within each level of collaboration in a  socio-technical environment like clinical context (Ruscio, 2024 -- GALA Framework). More recent frameworks like GALA framework, emphasize that humans are increasingly supervising semi-autonomous systems rather than directly manipulating every action, and LoA must be reasoned at the same level of cognitive interaction and tasks hand-off. In rehabilitation where different levels of autonomous systems are integrated, informations are processed and functional decisions-are made without the awareness of therapists. ( i need better argument for this)

Many rehabilitation technologies already embody these implicit choices even when they are not described in the same terms. Exergame platforms with recommendation systems automatically select and plan personalized exercises based on performance histories, biofeedback and other data points, shifting agency from therapist to algorithms (use source from earlier here). _Find the recommendation exergame paper here and write_ . Similarly, XR-exergames use biofeedback, emotion recognition, and real-time performance analytics to adjust games difficult while therapists interfaces are treated as secondary tools for configuring high-level therapy goals and evaluation. More-than-human perspectives make these design decisions visible by exposing how exergame systems, algorithms, workflow, and even organizational constraints contribute in shaping who is "in", "on", or "out of" the loop in different phases of therapy rather than treating automation simply as a means for efficiency. Additionally, these studies are still approached from anthropocentric perspective and fail to consider the inevitable future in which the networked computational components are continuously informed by algorithmic logic without human oversight. We need to ultimately be open to conversation about possible future instead of a single inevitable future. 

// https://inria.hal.science/hal-03630916/document
//https://link.springer.com/chapter/10.1007/978-3-319-58071-5_4
// we ultimately need to make the shift from thinking about an inevitable future to being open to a critical and creative conversation about possible futures (in significant plural) (Giacardi & Redström 2020)





