
= Background
This section presents relevant research and frameworks to establish* an overview of research on therapist interfaces for rehabilitation through exergames.* The chapter covers the following areas: (1) Exergames & Automation in Rehabilitation, (2) More-than-Human Agency, and (3) Therapist Interfaces for Exergame-Based Therapy.


== Exergames & Automation in Rehabilitation
Exergames, a fusion of "exercise" and "video games", are video games that promote physical activity and cognitive engagement through gamified tasks @ohyou2010. Although not exclusively, they are often classified under a broader category "Serious Games", which refers to digital games designed primarily for purposes beyond entertainments, such as education, training, and health interventions @Maggio2025. The researches also differentiate between commercial off-the-shelf systems and custom systems used for rehabilitation purposes @Allegue2022. The meta-analyses show exergames systems specifically designed for rehabilitation tend to be more effective than conventional therapy, whereas re-purposed commercial off-the-shelf systems often yield mixed or neutral results, in part because their interaction mechanics and feedback are not tightly aligned with therapeutic goals @Maier2019. *Exergames* have shown to support neuroplasticity by enabling high repetition and high intensity task-oriented activities that are challenging enough but not frustrating resulting in increased motivation and engagement  @Maier2019 @Allegue2022 @Shah2022. 

A wide range of technologies have been explored to implement exergames for rehabilitation. Non-immersive systems based on Xbox Kinect, Nintendo Wii, PlayStation, Robot-assisted serious games, or similar motion-sensing consoles are widely studied and have shown be be clinically provide effective rehabilitation compared to conventional therapy @Cheok2015 @Santos2025 @Doumas2025. Similarly, XR-based exergames, which are more immersive in nature, have been used for motor and cognitive rehabilitation after stroke and other neurological conditions, with studies reporting improvements in motor functions, spatial attention, and improved engagement compared to conventional exercises @Fordell2016 @Faria2016. Additionally, automation of various work processes is increasingly transforming modern workplaces in rehabilitation, with many functions now being carried out either partially or fully by automated systems @TurmoVidal2025 @Yu2026. These automated data-driven systems support personalized rehabilitation, and reduce therapists workload while preserving the human aspects and judgement. Exergame platforms with recommendation systems automatically select and plan personalized exercises based on performance histories, biofeedback and other data points, shifting agency from therapist to algorithms @Ismail2021 @Zhao2020. Similarly, XR-exergames use biofeedback, emotion recognition, and real-time performance analytics to adjust games difficult while therapists interfaces are treated as secondary tools for configuring high-level therapy goals and evaluation. These studies demonstrate that exergames can be implemented and are being explored in varied technologies including across different rehabilitation settings while automation in the these systems are enhancing the work process to provide personalized rehabilitation. 

These new developments are often discussed using the notions of human-in-the-loop (HITL), and human-on-the-loop (HOTL). In HITL, humans are embedded in the control loop and must initiate, approve or adjust system decisions before they are executed or can move forward in the workflow. For example, when a therapists manually selects the exergames and its parameters or when a therapists manually checks and approves the exergames suggested by a recommendation system. In HOTL, the system operates autonomously while human monitors and intervene when required. For example, when an exergame system continuously adjusts game parameters based on patient performance or biofeedback while the therapist supervises through their own interface @Lazaros2026. Classic Level of Automation (LoA) taxonomies present how functions are divided between human and AI @AitMalek2020. These frameworks are tools to understand implications and challenges within each level of collaboration in a socio-technical environment like clinical context @Ruscio2024. More recent frameworks like GALA framework, emphasize that humans are increasingly supervising semi-autonomous systems rather than directly manipulating every action. As mentioned previously, many rehabilitation technologies already embody these implicit choices even when they are not described in the same terms.

// elaborate on human-in-the loop (section 4.1 immediacy)
Despite the mutual determination of humans and computer, the characterization of interaction is still tied to human intentionality, even when human agency, human-in-the-loop, and intentionality are no longer the only perspectives considered within the fourth wave @Comber2019. 

// Additonally, These autonomous systems powered by AI and ML process information and make functional decisions in a "black box", without the awareness of therapists. These can give rise to algorithmic bias. 
 
Beside providing a gamified exercise and its effectiveness in clinical treatment, exergames can also viewed as interactive systems that generate performance data which can be used to monitor progress and support clinical-decision making. Exergames inherently generate fine-grained performance data (like reaction times, errors, speed) that can be used to adapt game logics in real-time or to monitor progress and support clinical decision-making process across sessions @Ismail2021. It aids how interfaces, algorithms and workflows can be designed to support personalized rehabilitation alongside providing gamified exercise experience @AttohMensah2025. Exergames thus have higher potential of accurately providing and utilizing data-centric monitoring during therapy sessions and create adaptable and fun experiences to fit individual needs allowing patients to participate in interactive and adaptive exercises @Rahin2025. One way that has been done is through AI and Machine learning approaches as they have the ability to enable precision medicine by analyzing sensors, game data and performance data to recommend or automatically adjust therapy parameters such as task type, difficulty, movement or session length @AttohMensah2025. However, treating personalization as a purely technical optimization and user experience problem would be short-sighted without considering patient preferences, motivational factors and meaningful therapeutic goals. 

// subjective and objective data. 
These subjective information like patient preferences and feedback, patient motivation, physical and psychological state, and therapists' own work and life experience were among the factors that played crucial role, as well as prioritized, in clinical reasoning of physiotherapists besides just objective data (both motor and physiological). This clinical reasoning helped them set patient goals, decide of treatment plan and adjust rehabilitation sessions @Molle2025 @Holdar2013.  However, novice therapists relied more on informative but objective factors for clinical decision-making compared to experienced therapists, who considered both subjective and objective data to provide personalized rehabilitation @Holdar2013. This highlights the need to either incorporate or consider subjective data when developing technology for therapeutic process, suggesting therapists should be in the loop instead of adopting full automation @Molle2025. 

// Include TA 
*This factor is important an to implement within the system as well as the connection and relationship between the therapist and patient*, referred to as therapeutic alliance (TA) is identified as a crucial determinant of engagement in rehabilitation @Kayes2012.

//connect with below section

== More-than-Human Agency 

From more-than-human perspective in HCI, computational systems can be viewed as co-creators of actions, phenomena, and experiences, and not just as tools "used by" humans @Frauenberger2019. 

Computational systems are no longer just tools "used by" humans, rather they are co-creators of actions, phenomena and experiences @Frauenberger2019. In relation to these systems, humans are not acting alone. The fourth wave emphasizes the need to move away from the notion of human-centered design where humans are *autonomous* decision-makers interacting with neutral tools, or view computational systems as autonomous tools that simply replace humans. Instead*, the 4th wave* view them as co-performers where humans and computational systems continuously shape each other and perform social practices together @Frauenberger2019 @Kuijer2018. As such, agency is not something human posses individually or independently, but rather relational and distributed across relationships between humans, technologies, institutions, environments, and norms. 

Therefore, from a more-than-human perspective, agency in rehabilitation can be presented as distributed across humans (therapists and patients) and non-humans (such as exergame systems, algorithms, interfaces, sensors, data representations, institutions, and even regulatory frameworks, rather than being possessed by any single actor @GiaccardiRedstrom2020 @Frauenberger2019. As these system become more data-driven, healthcare decisions are increasingly influenced by algorithmic logic and historical data apart from just therapist reasoning @Jones2023. This means, in the context of exergame-based rehabilitation, therapy outcomes would be shaped not only by therapists' decisions and patients' performance, but also by how algorithms classify performance, how data is presented, what data is shown or hidden, what technology is used, and even institutional and legal constraints. This reiterates the fact that design in therapeutic scenarios is more about configuring relationships and agencies among multiple human and nonhuman actors over time, rather than just optimizing features within an interface. 

The sense of agency can be affected by factors such as timing, predictability, and level or form of automation @Legaspi2024; @Limerick2014. Experimental studies indicate that higher level of automation and increased cognitive workload are associated with reduced sense of agency, whereas thoughtfully designed hybrid interactions can maintain a stronger feeling of control even when system is acting on user's behalf @Howard2016 @Legaspi2024. These findings are particularly relevant in clinical contexts where therapists must be able to stand by decisions, both ethically and legally, even when those clinical decisions are mediated by automated systems. It is emphasized that clinicians should still be able to intervene when co-performing with AI, because legal and ethical responsibility for decisions currently remains with them @Olawade2026. The human agency is thus not replaced by AI because it is central to the process and continuously negotiated with the system @Frauenberger2019. Although, delegating more decision-making to the autonomous systems can create power imbalance. Additionally, there is a positive correlation between frequent reliance on AI tools and reduced clinical reasoning or decision-making skills and actions @Gerlich2025. For this reason, a more balanced approach where systems "performs" but the judgement of what is good, bad, or appropriate ultimately remains with the humans is recommended @Kuijer2018.

== Therapist Interfaces for Exergame-Based Therapy - phases <therapistinterfaces>
Various therapist interfaces for personalized rehabilitation through exergames have been developed, although they do not account for the entirety of the therapy process as they mainly focus on data documentation and/or session planning and task manipulation. One therapist interface for Village Druid VR, a therapy game used for rehabilitation was prototyped along through 2 co-design sessions with 2 therapists each. The lo-fi and hi-fi prototypes focused on patient data documentation for monitoring and progress evaluation as well as some simpler personalization session parameters which were not clearly defined @Ferreira2022. Similarly, #cite(<Duval2022>, form: "prose") redesigned an already existing conventional VR game, Spellcasters, through co-design sessions with 14 medical professionals (PT's & OT's). The re-purposed version of Spellcasters focused again solely on data documentation deemed valuable by the medical professionals, and task management through custom rehabilitative gestures to adjust relevant variables including scale, shape, direction and depth.

Another more elaborative study developed a set of collaborative VR serious games, 4 in total, both for upper-limb physical rehabilitation and cognitive rehabilitation of stroke survivors. Again, their framework ADAPT (Adaptive Dynamics for Activity-based Personalized Therapy) only focused on personalized session planning and some game task parameters. For the session planning, therapists could adjust the number of participants, the selection and sequencing of games, session durations and individualized goals. For game task parameters, the therapist could adjust level of difficulty and more detailed adjustments in complexity such as the number and type of objects or puzzle pieces, and in-game payment processes @Figueiredo2025-ADAPT. 

One study in particular fully isolated game task adjustment in the form of difficulty parameters only. Difficulty in classification in levels were found to lead to longer playtime with more fun and higher performance when compared to high-commitment game parameter goals in terms of goal and time @Eckert2023. #cite(<GagnonRoy2025>, form: "prose"), on the other hand co-developed COOK, a cognitive assistance system together with occupational therapists to help patients regain the ability to prepare meals. Although not an exergame, the patient still has a personalized interface with step-by-step instructions to follow where breaks, reminders and recipe-steps are all pre-configured by the therapist. 

With one exception, previous research does not account for how to share the agency between the therapist and the system. #cite(<Figueiredo2025HybridControl>, form: "prose"), the exception, highlight in their study that 7 out of 10 participants preferred a hybrid mode combining both automated and manual adjustments, however focused on task personalization only as well. Furthermore, while data documentation does improve evaluation and decision-making and personalized therapy and decision-making, ultimately improving patient care @Tadas2023 @Dowding2015, the current systems still remain very fragmented as they lack a holistic view of all the main phases in the therapeutic process. The Occupational Intervention Process model includes (1) Evaluation and Goal-Setting Phase, (2) Intervention Phase, (3) Reevaluation Phase @Hinojosa_Kramer_Royeen_2017 @fisher2009occupational. Physiotherapy largely uses the same basic structure and is often referred to as the "rehab cycle" or "SOAP" which also includes (1) Assessment and goal setting, (2) intervention and (3) re-evaluation @Negrini2019 @Physiopedia. 

Existing rehabilitation systems are fragmented across different platforms for assessment, therapy, and documentation. Furthermore, the current therapists interfaces for exergame rehabilitation system primarily focuses on adjustable parameters, dashboards, automated adjustments, effective recommendations, rather than on how control and responsibility are shared between therapists and computation systems across the full therapeutic process. 








//More-than-human perspective proposes therapeutic process is a socio-technical envrionment a


//Therapeutic process, as mentioned earlier, is a socio-technical environment, 

//From More than human should look at the entire process, and not just the interfaces or the agency distributed between people and system as a fixed constant...also refer to fraunberger on how these agency distribution is a neogtiation and situational..  


//agency is not a static property of subjects or objects, but a dynamic, practice-based and relational capacity that is exercised in concrete performances and socio-material configurations. Human and artificial entities both participate in enacting practices and realities, but humans retain a distinctive role in judging and negotiating what counts as appropriate, ethical, and desirable forms of those performances

