// Go back to background ... see if the results contrdict, extend, agree with the background
// the point of discssion is methodological dicsussion and change in co-design based on results. what was insights

= Discussion
// background info, research purposes, methodology
This study examined how therapists reason about their agency in relation to a human-AI system, and how this agency was negotiated across the main phases of exergame-based rehabilitation. To investigate this, the study combined contextual inquiries with speculative co-design sessions in collaboration with clinical physiotherapists, clinical occupational therapists, and informants from Brain Stimulation, the case of study who develops XR exergame-based rehabilitation system. The discussion is organized into five main parts: (1) key findings are presented and summarized, (2) these findings are related to existing literatures as well as interpreted to address the research questions, (3) implications for design are presented with recommendations for the design of AI-supported exergame-based rehabilitation systems, (4) description of this study's limitations and (5) future research is discussed. Overall, this discussion aims to not only inform the design of future rehabilitation systems, but also to the understanding of how agency between human and AI can be configured throughout the rehabilitation process.

== Key Findings
//consensus
The accumulated results of this study's contextual inquiry and co-design sessions suggests a positive outlook on exergame-based rehabilitation and a cautious outlook on AI-supported digitalized rehabilitation, with a consensus that it is an inevitable future. The sense of inevitability was due to the technological advances in AI and its quick implementation in various fields. While viewing AI-supported rehabilitation as an inevitable future, they still hoped it would provide higher accessibility through remote rehabilitation for patients that live far, can not visit often or can not afford. The participants also concluded that exergame-based rehabilitation enables more effective personalization and high exercise repetitions, while simultaneously appearing fun and motivating for the patients, enabling precision rehabilitation. Subsequently, reducing time consumption and effort, a common and critical constraint within the rehabilitation field, which was also considered as a major key benefit. Due to this combination, all participants emphasized they would be willing to accept the AI system's therapy plan and all additional parameters even if imperfect if under time pressure, and if the required effort would otherwise be too high. There was however a clear non-negotiable to this condition, namely as long as patient safety is not compromised. This trade-off was however, only considered if the additional time and effort put, would not provide significantly better outcomes for the patient. 

Moreover, there were conditions to the shared therapist-system agency relating to autonomy and control. In particular, participants preferred shared agency in the form of system recommendations which required therapists' to accept, adjust or reject (_S2_) and, a system which requires instructions/prompts by the therapists' (_S3_) as they felt more in control. As opposed to the fully AI system (_S4_) which majority of participants were strongly opposed to, perceiving a strong threat towards their professional role and expertise - despite knowing they could override the system by accepting, adjusting or rejecting as well. Only two participants were comfortable with the fully AI system (_S4_), elaborating they would not feel replaced, but rather allow them to focus the additional time and effort on patient goals instead. Irrespective of participants' individual concerns, they were overall only willing to let go of control if there was scarcity of time, which is a common constraint in healthcare system, and level of trust in the system, something that can only be built over time and based on the results it consistently produced. The emphasis on acquired control was argued to assure better adaptation to each patient as every patient and day is unique. Another concern was how overreliance on this type of system could potentially reduce clinical reasoning skills, especially for novice therapists across all scenarios with partial or full agency (_S2, S3, S4_). 

Although there was an overall obvious preference for a system with agency in reasoning (_S2_) and a system with agency in execution (_S3_), the system requirements varied across the four main phases of rehabilitation. During _Assessment & Goal-Setting_ phase, participants generally preferred higher self-agency mainly through manual control without any system support (_S1_) or by providing instructions to the system (_S3_). During _Session Planning_ phase however, participants wanted less manual control, and more system with hybrid control structure where the system either held agency in reasoning (_S2_) or agency in execution (_S3_). On the other hand, for the _Rehabilitation Session_, participants wanted to delegate the system more agency in reasoning (_S2_) along with some agency in execution (_S4_), intervening manually only when absolutely necessary. Finally, for the _Post-Session Evaluation_, participants wanted the least amount of manual control (S1), mainly preferring agency in reasoning (_S2_), with some agency in execution (_S3, S4_). Surprisingly, system with full human agency in reasoning and execution (_S1_) was picked even less than full system agency in reasoning and execution (_S4_) despite the fearful thoughts of possible replacement by AI.

Another factor which affected the participants sense of agency was related to details of the information available on the various systems (_S1-S4_). All participants revealed a need for a lesser degree of details whether the system required full human agency in reasoning and execution (_S1_), human agency in execution with system agency in reasoning (_S2_) or system agency in reasoning with human agency in execution (_S3_). Instead of fine-grained details as default, participants only wanted curated information that relate to functional diagnostic goals to sustain a natural workflow and mental-model of a therapist. Nevertheless, participants still wanted the option for more in-depth information and parameter options when needed, suggesting a preference for a balanced design which combines hierarchal importance and simplicity. Access to additional in-depth information was also deemed important when there was uncertainty or a disagreement with the system, particularly for valuable for novice therapists. This was beneficial because it could help the therapist reflect, learn and understand why there was a difference in reasoning (_S2_), what changes the system made based on their instructions (_S3_) or deduce if they might have missed something. On the contrary, derived from the lack of trust, participants wanted a much higher degree of detail for the fully AI system (_S4_). As such, fully understanding that the system is accurately reasoning or executing the necessary actions correctly was perceived as crucial to assure that patients were receiving safe and qualitative rehabilitation. The only time details felt like a burden to the therapists, was when they themselves had to provide the system with detailed input (_S3_). 

Additionally, while AI-supported exergame-based system was advocated for, participants underscored how it still can not cover for all the necessities for a successful rehabilitation. The patient-therapist relationship specifically, was predominantly reported as something that could not be substituted with a system. The participants argued that the relationship is necessary for creating better motivation and trust, this increases the likelihood of consistent and correct rehabilitation. The weight of building a strong patient-therapist relationship resulted in participants willing to see the patient without any additional patient-data provided by the system, rather than having access to that data but not seeing the patient. Meeting the patient was also considered essential to control progress, provide and receive feedback which participants were skeptical any system could do. This was justified through the significant time patients spend outside of active rehabilitation in any given day, something that is usually not accounted for in the patient-data provided by the system. The only case where participants could consider not seeing the patient was again related to trust in the system to provide correct and effective rehabilitation without compromising ethical or security measures. 

Lastly, the participants' medium preference was less about the type of technology and more about the existing learning curve, accuracy and quality of data, as well as portability to support their day to day workflow which requires them to frequently switch rooms. Therapists took notes on paper and not any particular technology. Later transcribed to technology. The medium preference was for something they are familiar with to reduce learning curve, and reduce the stress resulting from technical issues. Instead, more emphasis was put into how they preferred a single system that looked at the entire rehabilitation process, rather than the existing fragmented ecosystem which separates phases into different systems such as journaling, assessment and rehabilitation systems.

== Therapists' Sense of Agency in Human-AI Rehabilitation System (RQ1)

Overall, the sense of agency in a AI-supported exergame-based rehabilitation system was an indispensable element for the participants as it supports them in delivering adaptive and effective therapy to their patients. The underlying reasons to this perception was however mixed and highly dependent on time and effort extorted by the therapist. On the one hand, participants were willing to let go of control to the system due to the workload demands and limited time resources within their rehabilitation field. On the other hand, majority of participants expressed feelings of threat, mainly by being undermined or possibly substituted by the AI if the work process were to be fully automated - even if they could intervene and override when necessary. Simultaneously, the fully AI system (_S4_) was still picked more than the system with full human agency (_S1_) despite participants wanting to remain in control. This apparent contradiction could explain by differentiating the sense of agency from agency distribution. Therapists still retained the sense of agency despite AI taking operational control, if they maintained capacity to set patient goals, boundaries and become accountable for the outcomes. Their sense of agency was maintained by retaining this cut, not by performing every action, indicating a need for shared agency through hybrid control where the system can assist in either reasoning or execution, rather than being fully replaced.

Another factor which affected the therapists sense of agency related to their ability to, on demand, access additional and more detailed information on the reasoning behind the systems recommendations and actions. This requirement was largely driven by skepticism regarding the systems reliability to actually provide correct recommendations and actions, which was especially the case when the system was fully AI. Participants described this trust to be built over time and consistent results. In a way, trust was bound up with transparency. Moreover, if disagreements or uncertainties occurred, participants were adamant in needing more detailed information to investigate and understand the difference in opinion. We therefore believe the participants seek a system which decreases the "black box" nature of AI-supported systems. This can be done through Explainable AI (XAI), a method which proposes to improve transparency, trust, reliability and interpretability @Arrietaetal2020. However, we want to point out that XAI can also affect the mental model of the user, and potentially even increase noise in decision-making @Bauer2023. 

Interestingly, the type of information was also equally important to the participants in building or dismantling trust in any of the automated systems. A common language in the form of functional and diagnostical information, rather than numerical or technical information would signify a higher shared understanding between the therapist. In the absence of a common language and clean information hierarchy, participants reported risks for disrupted workflow resulting in frustration and possibly affected rehabilitation sessions. Their sense of agency was not dependent on level of detail but the quality of the details, while the lack of shared mental-model or language reduced the felt control. Additionally, the excessive details was also seen as a burden when the participants had to input it, which explains their willingness to accept a shared agency and provide operational control to the AI-system. As mentioned, the participants in our study accepted the system's plan despite a reduced sense of agency when under time pressure. While this led to a decreased workload, it also decreased participants sense of agency, however they still had willingness to delegate the system. These findings extends how the need for sense of agency also decreases with both high mental workload and higher level of automation @Zanatto2021 @Limerick2014. They were not selecting level of automation, as the level-based frameworks @Ruscio2024 @AitMalek2020, but deciding where to draw the boundary between their involvement and system involvement for clinical reasoning and execution.

Conversely, while wanting to depend on the system, participants revealed that any degree of automated system could result in an overreliance which might inadvertently affect their own clinical reasoning, decision-making skills and actions @Gerlich2025. The harshest and most destructive consequences of this overreliance was according to our participants for the novice therapists, who rely more on informative and objective factors and are still in the process of learning the rehabilitation processes, reasoning and decision-making skills @Holdar2013. Perhaps this could be counteracted by avoiding delegation of clinical reasoning and decision-making for novice therapists, until they feel confident in their clinical skills. Essentially, the novice therapists who would gain most from system's reasoning are also the one who should avoid it the most to preserve critical thinking. This also emphasizes the need for AI to complement the therapists work rather than hinder their critical thinking and clinical decision making. Additionally, the repeated preference for the portable medium was not for aesthetic reasons but for practicality as it supported their movement from room to room across multiple patients, thereby aiding their sense of agency to provide quality care. 

Remaining in control and not being fully substituted by the system was also argued to be vital in fostering a good and trusting patient-therapist relationship. This was said to boost adherence, trust and motivation to actually perform rehabilitation consistently as the "Therapeutic Alliance" (TA) is a necessity for rehabilitation @Kayes2012. Furthermore, our results are also consistent on how therapists take subjective data into account more than the objective data @Molle2025 @Yu2026. This is given the impact that patient preferences, feedback, physical and psychological states among other factors affect clinical reasoning, goal-setting and therapy plan @Molle2025 @Holdar2013. Here, again, the therapists intentionally drew the cut to preserve the TA and to remain accountable for rehabilitation decisions and outcomes. This explains why our participants repeatedly picked meeting the patient over additional objective data provided by the system. It also explains why they perceive the interaction between themselves and the patient to be vital for successful rehabilitation and which should not be replaced by AI.
  
== Agency Distribution Across The Main Phases (RQ2)

When it comes to agency distribution across the main phases of rehabilitation, the findings suggest that therapists do not have a single, stable preference for control. Instead, their preference varied on in which rehabilitation phase they are in. This is consistent with the theory of co-performance, and helps reconceptualize therapists and AI system as co-performers whose roles and responsibilities shift as the rehabilitation process evolves rather than being a fixed configuration @Kuijer2018. When the therapists reasons which phase the system should reason or execute, they are not merely stating a preference, rather they are drawing an agential cut by enacting a boundary between their agency and AI agency. Thus, the finding extends co-performance as phase-dependent as agency is not allocated once but repeatedly drawn and re-drawn as the practice unfolds.

In the first phase, where understanding the patient motivation, deciding on long-term patient goals, and planning treatment are important, the therapists favored full human agency in reasoning specifically (_S1, S3_). This reflects the therapists' need to reconcile the subjective information from the patient, like patient motivation and life context, which are difficult to externalize into data. This phase also correlates how therapists see as their primary role and central to their professional identity. As the reasoning becomes distributed or even led by AI-system, the nature of "expert" becomes less clear and could be perceived as threatening as it destabilizes the therapists' role as the primary decision-maker @Frauenberger2019. Our findings extends this argument into exergame-based rehabilitation showing therapist explicitly draw a cut resisting giving the role of primary decision-maker.

When planning the session, therapists' preference shifted to increasingly accepting, and even preferring, system-led reasoning and/or execution (_S2, S3_), as long as they retain the ability to intervene. Participants framed _session planning_ as repetitive and time-consuming, especially in a time-constraint situation. The system support is seen as valuable for selecting and sequencing exercises consistent with the main rehabilitation goals. For rehabilitation sessions itself, participants were most willing to delegate agency in reasoning (_S2_) while some even accepted full system agency (_S4_) choosing to intervene only when necessary. _Rehabilitation sessions_ are especially cognitively demanding to adjust exergame parameters while simultaneously monitoring patient performance. Adaptive systems supported by ML that can perform dynamic difficulty adjustment based on patient performance and other signals could be useful. It aligns with the human-in-the-loop healthcare AI studies where automation is deemed most acceptable when the system manages low-level and continuous tasks while therapists supervise @Olawade2026 @Lazaros2026. Even as AI system gradually take over repetitive and low-level tasks, the therapists still retain the sense of agency through the capacity to define goals and constraint, intervene when deemed appropriate and provide final judgement. 

However, in the _post-session evaluation_ phase, they wanted the least amount of manual control, strongly favoring system-led reasoning (_S2_), with some agency in execution (_S3,S4_). This could indicate the participants felt the system could efficiently reconcile data across tasks and sessions, and analyzing trends and progress than them doing it manually. The lesser degree of preference in delegating execution shows that they still prefer to interpret the results themselves and decide if plans needs to be adjusted. Studies on AI-supported Clinical Decision Support Systems (CDSS) shows clinicians trust the system to handle administrative and analysis tasks but prefer to retain the control for interpretation and final decision @Jones2023. 
 
Across all four main phases, the observed pattern is not a simple increase in automation, but a dynamic hybrid arrangement in which agential cut is being drawn to the demands and purposes of each phase. Additionally, therapists phase-dependent preferences highlights discrepancies between what therapists desired and how current exergame-based rehabilitation systems are structured. Existing exergame systems tend to focus on automation and detailed parameter control within the _Rehabilitation Session_, while focusing less for phases like _Assessment and Goal-Setting_, and _Post-Session Evaluation_ @Figueiredo2025HybridControl @Ferreira2022. Moreover, these systems are further fragmented across assessment, rehabilitation, and documentation, which increases learning costs and therapists' sense of familiarity. While these systems define a static cut splitting the process between human and system, our participants wanted the unified rehabilitation system where this agential cut is configurable across the whole rehabilitation cycle, rather than a constant level of automation @AitMalek2020 @Ruscio2024. Finally, these findings suggest that exergame-based rehabilitation system agency distribution should be designed to be adaptable, phase-sensitive with hybrid agency distribution across the phases rather than having automation as a constant across all phases. @Kuijer2018. 
 
== Implications for Design <designimplications>

The central implication for design is that AI-supported exergame-based rehabilitation systems should not be designed around a fixed level of automation but around how agency can shift across the different phases of the rehabilitation for therapists' to retain the sense of agency. The design problem is not how much to automate through AI but how to make this agential cut easily configurable by therapists, phase, and under shifting conditions of time, trust, and level of detail. 

*_Phase-dependent co-performance_:* The cut should be defined per phase and not defined as a fixed division. Human-led during _Assessment & Goal-Setting_, Shared in _Session Planning_ and _Rehabilitation Session_, and System-Led for analysis in evaluation. This implication is only applicable where the rehabilitation practice is structured and cyclical, and might be less applicable where the phase boundaries are not clear. 

*_The agential cut is enacted and not fixed_:* The sense of agency is supported by retaining the ability to re-draw the cut. This ability to make the cut i.e. intervene, adjust, and override should be an always-present action, and not buried under settings. The availability of this intervention matters as much as its use.

*_Default to Less, but provide for more_:*  Provide curated view, natural, functional and diagnostical language by default to avoid unnecessary cognitive load. However, maintain the option to elaborate on system's reasoning and system's execution process on demand, especially when human is interrogating a cut they did not draw. 

*_Autonomy based on trust:_* Avoid full autonomy as the default, as it was often associated with loss of control and weaker sense of agency, and thus a threat to the therapists' role as primary decision-maker. The position of this cut should only shift towards the system as the trust builds, with conservative cut for novice therapist. The AI system can perform part of the practice, but it should ultimately not decide what is good, acceptable, or appropriate which should remain a human judgment.

*_Preserve Therapeutic Alliance:_* Reserve certain performances like observing, relating to, and being accountable to the patient to the human side of the cut by design, while treating the system as augmenting rather than mediating that relationship.  



