// Go back to background ... see if the results contrdict, extend, agree with the background
// the point of discssion is methodological dicsussion and change in co-design based on results. what was insights

= Discussion
// background info, research purposes, methodology
This study examined how therapists reason about their agency in relation to a human-AI system and how this agency was negotiated across the main phases of exergame-based rehabilitation therapy. To investigate this, the study combined contextual inquiries, including an observation, with speculative co-design sessions and a pilot study with clinical physiotherapists, clinical occupational therapists, and informants from Brain Stimulation, the company developing an XR-based rehabilitation platform. The discussion is organized into few parts. First, the key findings are presented and interpreted. Second, these findings are related to existing literatures to address the research questions. Third, design implications are presented with recommendations for the design of AI-supported exergame-based rehabilitation systems. Finally, the study's limitations and future designs are discussed. Overall, this discussion aims to provide insights not only to design to rehabilitation system, but also to the understanding of how agency between human and AI can be configured throughout the rehabilitation process.

== Key Findings
//consensus
The accumulated results of this study's contextual inquiry and co-design sessions suggests a positive outlook on exergame-based rehabilitation and a cautious outlook on AI-supported digitalized rehabilitation,*while agreeing it was an inevitable future*. They agreed exergame-based rehabilitation enables more effective personalization and high exercise repetitions, while simultaneously appearing fun and motivating for the patients, and digitalized rehabilitation would enable precision rehabilitation. Subsequently, reducing time consumption and effort, a common and critical constraint within the rehabilitation field, was also considered as a major key benefit. Hence, all participants emphasized that under time pressure if the required effort would otherwise be too high, they would be willing to accept the AI system's therapy plan and all additional parameters even if imperfect, but with condition as long as patient safety was not compromised. This trade-off was however only considered if the additional time and effort put, would not provide significantly better outcomes for the patient. While viewing AI-supported rehabilitation as an inevitable future, they hoped it would provide higher accessibility through remote rehabilitation for patients that live far, can not visit often or can not afford.

In spite of the positive attitude towards AI-supported exergame-based rehabilitation, there were conditions to the shared therapist-system agency relating to *the sense of* autonomy and control. In particular, participants preferred shared agency in the form of system recommendations which required therapists to accept, adjust or reject (_S2_) and, a system which requires instructions/inputs by the therapists (_S3_) as they felt more in control. As opposed to the fully autonomous system (_S4_) which majority of participants were strongly opposed to, perceiving a strong threat towards their professional role and expertise - despite knowing they could override the system by accepting, adjusting or rejecting as well. Only two participants were comfortable with the autonomous system, elaborating they would not feel replaced, but rather allow them to focus the additional time and effort on patient goals instead. Irrespective of participants' individual concerns, they were overall only willing to let go of control if there was scarcity of time, which is a common constraint in healthcare system, and level of trust in the system, something that can only be built over time and based on the results it consistently produced. *The emphasis on acquired control was *argued* to assure better adaptation to each patient as every patient and day is unique.* *Another concern was how overreliance on this type of system could potentially reduce clinical reasoning skills, especially for novice therapists.* // was this only for AI or for all scenarios?? 

Although there was an overall obvious preference for a system with agency in reasoning (_S2_) and a system with agency in execution (_S3_), the system requirements varied across the *four main phases of therapy*. During therapy planning & goal-setting (_Phase 1_), participants generally preferred higher self-agency mainly through manual control without any system support (_S1_) or by providing instructions to the system (_S3_). During session planning (_Phase 2_) however, participants wanted less manual control, and more system with hybrid control structure where the system either *managed* agency in reasoning (_S2_) or agency in execution (_S3_). On the other hand, for the rehabilitation session (_Phase 3_), participants wanted to delegate the system more agency in reasoning (_S2_) along with some agency in execution (_S4_), intervening manually only when absolutely necessary. Finally, for the post-session evaluation (_Phase 4_), participants wanted the least amount of manual control (S1), mainly preferring agency in reasoning (_S2_), with some agency in execution (_S3_ & _S4_). Surprisingly, system with full human agency in reasoning in reasoning and execution (_S1_) was picked even less than full system agency in reasoning and execution (_S4_) despite the fearful thoughts of possible replacement by AI. //Mention the discrepancies were present between what they desired and what was designed.

Another factor which affected the participants sense of agency was related to details of the information available on the various systems (_S1-S4_). All participants revealed a need for a lesser degree of details whether the system required full human agency in reasoning and execution (_S1_), human agency in execution with system agency in reasoning (_S2_) or system agency in reasoning with human agency in execution (_S3_). Instead of fine-grained details as default, participants only wanted curated information that relate to functional diagnostic goals to sustain a natural workflow *(parameters??)* and mental-model of a therapist. Nevertheless, participants still wanted the option for more in-depth information and parameter options when needed, suggesting a preference for a balanced design which combines hierarchal importance and simplicity. Access to additional in-depth information was also deemed important when there was uncertainty or a disagreement with the system, particularly for valuable for novice therapists. This was beneficial because it could help the therapist reflect, learn and understand why there was a difference in reasoning (_S2_), what changes the system made based on their instructions (_S3_) or deduce if they might have missed something. On the contrary, derived from the lack of trust, participants wanted a *much* higher degree of detail for the fully automated system (_S4_). As such, fully understanding that the system is accurately reasoning or executing the necessary *actions* correctly was perceived as crucial to assure that patients were receiving safe and qualitative rehabilitation. The only time details felt like a burden to the therapists, was when they themselves had to provide the system with detailed input (_S3_). 

Additionally, while AI-supported exergame-based system was advocated for, participants underscored how it still can not cover for all the necessities for a successful rehabilitation. The patient-therapist relationship specifically, was predominantly reported as something that could not be substituted with a system. The participants argued that the relationship is necessary for creating better motivation and trust, this increases the likelihood of consistent and correct rehabilitation. The weight of building a strong patient-therapist relationship resulted in participants willing to see the patient without any additional patient-data provided by the system, rather than having access to that data but not seeing the patient. Meeting the patient was also considered essential to control progress, provide and receive feedback which participants were skeptical any system could do. This was justified through the significant time patients spend outside of active rehabilitation in any given day, something that is usually not accounted for in the patient-data provided by the system. The only case where participants could consider not seeing the patient was again related to trust in the system to provide correct and effective rehabilitation without compromising ethical or security measures. 

Lastly, the participants' medium preference was less about the type of technology and more about the existing learning curve, accuracy and quality of data, as well as portability to support their day to day workflow which requires them to frequently switch rooms. Therapists took notes on paper and not any particular technology. Later transcribed to technology. The medium preference was for something they are familiar with to reduce learning curve, and reduce the stress resulting from technical issues. Instead, more emphasis was put into how they preferred a single system that looked at the entire therapeutic process, rather than the existing fragmented ecosystem which separates phases into different systems. Such as journaling, therapeutic assessment and rehabilitation systems.

//temporality ?

== Agency (?) (RQ1)

//With the increase in automation of process in rehabilitation, the design of shared agency between human and computational system becomes essential, especially within rehabilitation where agency is critical to support therapists work without undermining or substituting the autonomy and expertise. In this study, we contribute to this area of work by interpreting (1) how therapists reason about their agency in relation to AI-supported exergame-based rehabilitation system, and (2) how the shared agency should be designed throughout the four main phases of therapy. 

Overall, the sense of agency in a AI-supported exergame-based rehabilitation system was an indispensable element for the participants as it supports them in delivering adaptive and effective therapy to their patients. The underlying reasons to this perception was however mixed and highly dependent on time and effort extorted by the therapist. On the one hand, participants were willing to let go of control to the system due to the workload demands and limited time resources within their rehabilitation field. On the other hand, majority of participants expressed feelings of threat, mainly by being undermined or possibly substituted by the AI if the work process were to be fully automated - even if they could intervene and override when necessary. Simultaneously, the fully automated system (_S4_) was still picked more than the system with full human agency (_S1_) despite participants wanting to remain in control. These results aligns with *(source)* that also found the the sense of agency decreases with both high mental workload and higher level of automation. Hence, the reasonable outcome of our results indicating the need for shared agency through hybrid control where the system can assist in either reasoning or execution, rather than being fully replaced. This aligns well with the study done with AI-based clinical decision support systems (CDSS) where clinicians preferred systems that supports them, rather than replacing their key role of clinical decision-making (Jones et al., 2023).

Remaining in control and not being fully substituted by the system was also argued to be vital in fostering a good and trusting patient-relationship. This was said to boost adherence, trust and motivation to actually perform rehabilitation consistently as the "Therapeutic Alliance" (TA) is a necessity for rehabilitation (Kayes & McPherson, 2012). Furthermore, our results are also consistent on how therapists take subjective data into account more than the objective data (Molle et al., 2025). This is given the impact that patient preferences, feedback, physical and psychological states among other factors affect clinical reasoning, goal-setting and therapy plan (Molle et al., 2025; Holdar et al., 2013). This explains why our participants repeatedly picked meeting the patient over additional objective data provided by the system. It also explains why they perceive the interaction between themselves and the patient to be vital for successful rehabilitation.

Another factor which affected the therapists sense of agency related to their ability to, on demand, access additional and more detailed information on the reasoning behind the systems recommendations and actions. This requirement was largely driven by skepticism regarding the systems reliability to actually provide correct recommendations and actions, which was especially the case when the system was fully automated. Moreover, if disagreements or uncertainties occurred, participants were adamant in needing more detailed information to investigate and understand the difference in opinion. We therefore believe the participants seek a system which decreases the "black box" nature of AI-supported systems. This can be done through Explainable AI (XAI), a method which proposes to improve transparency, trust, reliability and interpretability *(Arrieta et al., 2019)*. However, we want to point out that XAI can also affect the mental model of the user, and potentially even increase noise in decision-making (Bauer et al., 2023).
 
Interestingly, the type of information was also equally important to the participants in building or dismantling trust in any of the automated systems. A common language in the form of functional and diagnostical information, rather than numerical or technical information would signify a higher shared understanding between the therapist and the system. We therefore believe that creating a system with common language could contribute to building reliability and trust while decreasing frustration due to the shared mental-model, which in turn allows both the human and the system to understand each others reasonings, instructions and actions. In the absence of a common language and clean information hierarchy, participants reported risks for disrupted workflow resulting in frustration and possibly affected rehabilitation sessions.
 
Conversely, while wanting to depend on the system, participants revealed that any degree of automated system could result in an overreliance which might inadvertently affect their own clinical reasoning, decision-making skills and actions (Gerlich, 2025). The harshest and most destructive consequences of this overreliance was according to our participants for the novice therapists who are still in the process of learning the therapeutical processes, reasoning and decision-making skills. This is because novice therapists rely more on informative and objective factors for clinical decision-making compared to more experienced therapists (Holdar et al., 2013). Perhaps this could be counteracted by avoiding delegation of clinical reasoning and decision-making for novice therapists, until they feel confident in their clinical skills. This can be done by... Turnn off AI, get hints if needed, to lessen degree of help by the AI.


  
== Agency distribution across the main phases (RQ2)

//#text(20pt, purple)[*RQ2:* How does this agency distribution vary across the main phases of therapy?]

When it comes to agency distribution across the main phases of therapy, the findings suggest that therapists do not have a single, stable preference for control in a *Human-AI system*. Instead, their preference varied on in which therapy phase they are in. In the first phase, where understanding the patient motivation, deciding on long-term patient goals, and planning treatment are important, the therapists favored full human agency in reasoning specifically (_S1,S3_). This can be interpreted as therapists' need to reconcile the subjective information from the patient to collaboratively set the goals and plan the entire therapy plan to provide personalized care for that patient. // need studies from patient perspective

When planning the session, therapists' preference shifted to... increasingly accept, and even prefer, system-led reasoning and/or execution (_S2, S3_), as long as they retain the ability to intervene. Participants framed planning as repetitive, especially in a time-constraint situation, provided they could still adjust it. They, similarly, framed executing the clinical decisions as hectic(?) and time-consuming. The system support is seen as valuable for selecting and sequencing exercises consistent with the main therapy goals. // need source to support it 
//This however aligns with their preference for less detail and only focus on higher level therapeutic decisions. 

For rehabilitation sessions itself, participants were most willing to delegate agency in reasoning (_S2_) while some even accepted full system agency (_S4_) choosing to intervene only when necessary. Rehabilitation time is especially cognitively demanding to adjust exergame parameters while simulateneously monitoring patient performance. Adaptive systems supported by ML that can perform Dynamic Difficulty Adjustment (DDA) based on patient performance and other signals could be useful. It aligns with the human-in-the-loop healthcare AI studies where automation is deemed most acceptable when the system manages low-level and continuous tasks while therapists supervise (Olawade et al., 2026; Lazaros et al., 2026).

However, in the post evaluation (_Phase 4_), they wanted the least amount of manual control, strongly favouring system-led reasoning (_S2_), with some agency in execution (_S3,S4_). This could indicate the participants felt the system could efficiently reconciling data across tasks and sessions, and analysing trends and progress than them doing it manually. The lesser degree of preference in delegating execution shows that they still prefer to interpret the results themselves and decide if plans needs to be adjusted. Studies on AI-supported clinical decision support systems (CDSS) shows clinicians trust the system to handle administrative and analysis tasks but prefer to retain the control for interpretation and final decision.
 
Altogether, therapists phase-dependant preferences highlights discrepancies between what therapists desired and how current exergame-based rehabilitation systems are structured. Existing exergame systems tend to focus on automation and detailed parameter control within the rehabilitation session, while focusing less for phases like collaborative planning and goal-setting, and evaluation (Figueiredo et al., 2025; Ferreira et al., 2022). Moreover, these systems are further fragmented across assessment, rehabilitation, and documentation, which increases learning costs and therapists' sense of familiarity. The lack of familiarity, as mentioned by participants, also decreases the sense of agency and increased unnecessary stress. In contrast, our studies shows therapists would like to have a single system that encapsulated the entire therapeutic process from assessment to evaluation. 

(RQ2) 
Finally, these findings suggest that exergame-based rehabilitaiton system agency distribution should be designed to be adaptable, phase-sensitive with hybrid agency distribution across the phases rather than having automation as a constant across all phases. 

//when designing technology, they should be designed for portability (medium-agnostic argument)

--------------------------------------------
 *write THIS last*  *DO NOT REMOVE COMMENT!!!!*
 *Perhaps the role of therapists still could remain as important despite full automation by transforming the current workflow going from decision-making to AI reviewers to serve the role as a controller and ...of therapy planning and X for assuring higher accessibility .*


 // conclude with more-than-human design
 - argue that people with less critical injuries who do not need to be overseen because of safety-reasons could use this type of technology being remote, might reduce the pressure on the rehabilitation centers --> more people get rehabilitation
// If the system includes X, Y and Z, one could potentially increase therapists ability to feel in control while increasing accessibility to rehabilitation through remote rehabilitation for patients that live far, can not visit often or otherwise could not afford rehabilitation.

// explain that if one does it correctly, our participants would be willing to trust the system to perform the rehabilitation if it does not compromise ethical or safety measures. necessity for building a system that does not compromise ethical or safety measures


== Design Implications 
Because [finding], the design should [principle/action] so that [user benefit].”

1. The design should support phase-specific agency distribution across all main phases of therapy.

2. The design should implement hybrid control model where system recommends and executes but therapists are in-the-loop to accept, reject, adjust instead of fully autonomous workflow.

3. The design should prioritize low-detail interfaces with access to additional detail on demand.  (for both input like instructions and output like recommendations, feedback and data). 

4. The design should include a common language in the form of functional/diagnostical information between the system and the therapist.

4. Optimize flow for minimal time and effort.. and maybe reduce stress on therapists. especially during and before sessions

5. design to build trust toward system over time?

6. include patient-therapist interaction important somehow? reduce ui complexity so that more focus on patient, simple control mechanisms, design screen layout so that user doesn't have to search for them.

7. how to design a system which therapists can rely on, without compromising their decision-making skills or clinical reasoning long-term?

8. want XAI

9. For medium-agnostic, it should be designed with portability in mind,.

10. Future prospects: the role of therapists still could remain as important despite full automation by transforming the current workflow going from decision-making to AI reviewers to serve the role as a controller and ...of therapy planning and X created by the system for assuring higher accessibility .

11. Option to turn off automation if required, especially for novice therapists. 










*IMPORTANT TO DO BEFORE SUBMISSION:*
//  reflect on how the results can contribute to the field of research. The reflection is characterized by an in-depth understanding of the results as well as related research
