== Study Limitations
This study has several limitations regarding the design of the study and the number of participants which should be acknowledged. To begin with, this study has applied only one case study, (Brain Stimulation), when investigating relevant therapist interfaces for rehabilitation through exergames. Brain Stimulation is a company who mainly focus on stroke-patients or patients with neurological conditions and mental fatigue through XR-based exergames, and while this provided in-depth understanding of one specific rehabilitation context, we believe that other relevant systems in other fields might differ significantly in terms of system interactions and processes, field, therapist needs and clinical workflows. Not accounting for other existing systems might therefore have created assumptions and insights tied to a single context, ultimately affecting the design of the co-design session including its dimensions and overall results and direction of this study. We however attempted to reduce this bias by reviewing research on existing automated systems within rehabilitation and therapists interfaces used for exergame-based rehabilitation. 

In regards to the co-design session, we believe that introducing one scenario after another to the participants might have affected how the later scenarios were perceived. Although the intention of doing so was to progressively expose the participants to the level of automation within the four scenarios, we are unsure if introducing the scenarios in reverse order from _S4-S1_ would have affected their perception and attitude towards the same scenarios. Additionally, while conducting the co-design sessions individually with the participants gave them enough time to think and elaborate their thoughts and opinions, we suppose that the results could be looking differently in group co-design sessions as participants could build upon each others interpretations. More collaborative discussion with diverse expertise could perhaps uncover perspectives that might have been overlooked in our individual co-design sessions. It could potentially even give insights into the conditions necessary for collaboration among colleagues within the system which was not discussed in the individual co-design session. Although there are potential benefits of conducting group co-design session, we believe that even those have their limitations such as biasness or group pressure from dominant individuals. This may lead to a limited range of perspectives rather than a comprehensive representation of all participants' views. We therefore believe that conducting individual co-design sessions was a strength as they allowed us to explore five different perspectives in-depth. 

While the results of this study are of qualitative nature, five participants are still too few to make any definitive and broad conclusions on which dimensions affect therapists sense of agency the most, or how the required agency distribution between human-machine should be through all four therapy phases. However, we still believe that the results of this study are highly reliable and qualitative as our participants had extensive experience with an average of *X years*. That said, the imbalance of 1 physiotherapist and 4 occupational therapists might have affected the understanding of the workflow and necessities for the agency distribution and needs for an AI-supported computational system for exergame-based rehabilitation across different therapeutic fields. 

// even though we were investigating the agency distribution in the scenarios to be medium-agnostic, not situated on any particular technology, since the images in the scenario 
the solution to that would be to present several images, representing different rehabilitation technology present and future, for each scenario to make the point clear 

Despite the limitations of this study, this research contributes meaningfully to the growing research on more-than-human design, *specifically in regards to human-AI collaboration in rehabilitation contexts.* First, the findings suggests that therapists are under certain conditions, okay with being less in control yet still maintain a sense of agency provided that their responsibility and care over the patient is not threatened. Second, the study contributes to a structured understanding of how agency could be dynamically distributed between therapists and an AI-supported computational system for exergame-based rehabilitation, as well as how agency could be distributed across the four main phases of therapy. Third, the proposed co-design framework and probe dimensions offer a conceptual foundation for future studies to further explore and build upon. *By centering therapists perspectives throughout the study, this research aids the development of AI systems that support rather than replace clinical expertise, human judgment and human decision-making.*

== Future Research
Future researchers and product designers could build upon the findings and address the limitations of this study through multiple avenues. Firstly, a more extensive contextual inquiry that looks at several case studies, with relevant therapist interface systems for rehabilitation through exergames, would be needed. Doing so could more accurately determine the therapist requirements and issues, clinical workflows, and system interactions and processes within various rehabilitation fields. Second, a higher number of participants for the co-design session with a balanced distribution between occupational therapists and physiotherapists who work with diverse patient conditions is needed. This could help provide a more accurate and definitive conclusion on the conditions required and necessary agency distribution between the therapist and system across the four phases, and within those different therapeutic fields. The co-design sessions should also be conducted individually and in groups to determine if and how group dynamics affect the sense of agency and how it should be applied within the four main phases of therapy. 

Moreover, to avoid affecting participants' perceptions and attitudes towards the scenarios of this study, the co-design sessions should also be performed with two focus groups. First, a control group where scenarios are presented as in this study from _S1-S4_ to see if the results remain consistent. Second, another group where scenarios are presented in reverse order from S4-S1 to determine if that affects their perceptions and attitudes. Furthermore, future studies should explore other additional dimensions beyond: (1) Agency in reasoning (2) Agency in execution, (3) Granularity, (4) Temporality (5) Interaction cost (6) Patient vs Data, (7) Materiality. We argue that incorporating additional insights, particularly those related to collaboration within socio-technical rehabilitation environments, would be essential to design a system that supports and mirrors the collaborative practices of therapists. Finally, the accumulated knowledge could then be used to create more robust and concrete design implications. These implications can then be used to design a provotype to further explore the agency distribution in relation to AI-supported computational systems for exergame-based rehabilitation. In such case, the extensive provotype should be tested in its natural settings at the clinic, but also in remote tele-rehabilitation settings to determine additional needs.