== Study Limitations
This study has several limitations which should be acknowledged. First, only one case study (Brain Stimulation) was used to investigate relevant therapist interfaces for exergame-based rehabilitation. While this provided in-depth understanding of one specific rehabilitation context, we believe that other relevant systems in other fields might differ significantly in terms of system interactions and processes, field, therapist needs and clinical workflows. We however attempted to reduce this bias by reviewing research on existing automated systems within rehabilitation and therapist interfaces used for exergame-based rehabilitation. 

In regards to the co-design session, we introduced scenarios (S1-S4) to progressively expose the level of automation within the four scenarios, which might have affected how later scenarios were perceived. We are hence unsure if introducing the scenarios in reverse order from _S4-S1_ would have yielded different results. Additionally, while conducting the co-design sessions individually with the participants gave them enough time to think and elaborate their thoughts and opinions, we suppose that the results could be looking differently in group co-design sessions as participants could build upon each others interpretations and provide perspectives about therapists collaboration. This may, however, lead to bias or group pressure from dominant individuals and a limited range of perspectives rather than a comprehensive representation of all participants' views. We therefore believe that conducting individual co-design sessions was a strength as they allowed us to explore five different perspectives in-depth. 

While the results of this study are of qualitative nature, five participants are still too few to make any definitive and broad conclusions on which dimensions affect therapists' sense of agency the most, or how the required agency distribution between human-AI should be through all four rehabilitation phases. However, we still believe that the results of this study are highly reliable and qualitative as our participants had extensive experience with an average of over 13 years. That said, the imbalance of 1 PT and 4 OTs might have affected the understanding of the workflow and necessities for the agency distribution and needs for an AI-supported computational system for exergame-based rehabilitation across different therapeutic fields.

Despite the limitations of this study, this research contributes meaningfully to co-performance, specifically to human-AI collaboration in rehabilitation contexts. First, the findings suggests that therapists are under certain conditions, willing to be less in control yet still retaining a sense of agency provided that their responsibility and care over the patient is not threatened. Second, the study contributes to a structured phase-dependent understanding of how agency could be dynamically distributed between therapists and an AI-supported computational system for exergame-based rehabilitation, and how it shifts across the four main phases of rehabilitation. Third, the proposed co-design framework and probe dimensions offer a conceptual foundation for future studies to further explore and build upon. By centering therapists' perspectives throughout the study, this research informs the development of AI systems that support rather than replace clinical expertise, human judgment and human decision-making.

== Future Research
Future researchers and product designers could build upon the findings and address the limitations of this study through multiple avenues. Firstly, a more extensive contextual inquiry that looks at several case studies, with relevant therapist interface systems for rehabilitation through exergames, would be needed. Doing so could more accurately determine therapist requirements and issues, clinical workflows, and system interactions and processes within various rehabilitation fields. Second, a higher number of participants for the co-design session with a balanced distribution between OTs and PTs who work with diverse patient conditions is needed. This could help provide a more accurate and definitive conclusion on the conditions required and necessary agency distribution between the therapist and system across the four phases, and within those different therapeutic fields. The co-design sessions should also be conducted individually and in groups to determine if and how group dynamics affect the sense of agency and how it should be applied within the four main phases of rehabilitation. 

Furthermore, future studies should explore other additional dimensions beyond: (1) Agency in reasoning (2) Agency in execution, (3) Granularity, (4) Temporality (5) Interaction cost (6) Patient vs Data, (7) Materiality. We argue that incorporating additional insights, particularly those related to collaboration, such as patients, colleagues and institutions, within socio-technical rehabilitation environments, would be essential to design a system that supports and mirrors the distributed agency of rehabilitation system. Finally, the accumulated knowledge could then be used to create more robust and concrete design implications. These implications could then be used to design a provotype to further explore the therapists' sense of agency in relation to AI-supported computational systems for exergame-based rehabilitation. In such case, the extensive provotype should be tested in its natural settings at the clinic, but also in remote tele-rehabilitation settings to determine additional needs.