= Statement for Conflict of Interest
This research has no conflict of interest as (1) the study was not funded by Brain Stimulation or any other organization, and (2) neither author has been employed by Brain Stimulation neither before nor during the course of this study.

= Conclusion
This study's purpose was to investigate how therapists reason about their agency and how it should be distributed across the main phases of exergame-based rehabilitation. The research questions were (1) How do therapists reason about their agency in relation to a human-AI system for exergame-based rehabilitation therapy?, and (2) How do therapists' preferences for agency distribution between themselves and a system (AI) vary across the main phases of exergame-based rehabilitation therapy *(e.g., therpay planning & goal-setting, etc)*. To answer the research questions, a participatory Research through Design (RtD) approach was implemented through two main methods: (1) a contextual inquiry conducted through a case study (Brain Stimulation) including interviews and observation, and (2) individual participatory speculative co-design sessions. Eight participants in total, with an average of *X years* were involved in the study: five participated in the contextual inquiry and five in the co-design session. The concluding results from the affinity diagramming indicate that under certain conditions, therapists' maintain a sense of agency in AI supported computational systems for exergame-based, provided that their responsibility and care over their patient is not threatened. The results also suggests that AI in exergame-based rehabilitation can not substitute the roles of therapists' as subjective factors and a therapeutic alliance (TA) is essential for successful rehabilitation. While the research sample is small, the participants and methods were of qualitative nature, thereby still reliably contributing to more-than-human design through the lens of therapists agency within AI-supported exergame-based rehabilitation systems'. We however suggest future researchers, product owners and students to continue to explore therapists sense of agency through more dimensions within all four phases of therapy to accurately determine the design implications for a *human-in-the-loop* AI-supported computational system for exergame-based rehabilitation.


// Ask pedro if conclusion needs to be shorter or not 

