= Statement for Conflict of Interest
This research has no conflict of interest as (1) the study was not funded by Brain Stimulation or any other organization, and (2) neither author has been employed by Brain Stimulation neither before nor during the course of this study.

= Conclusion
This study's purpose was to investigate how therapists' reason about their sense of agency and how agency could be distributed across the main phases of exergame-based rehabilitation. The research questions were (1) How do therapists' reason about their sense of agency in relation to a human-AI system for exergame-based rehabilitation?, and (2) How do therapists' preferences for agency distribution vary in relation to an AI system across the main phases of exergame-based rehabilitation?. To answer the research questions, a participatory Research through Design (RtD) approach was implemented through two main methods: (1) a contextual inquiry conducted through a case study (Brain Stimulation) including interviews and an observation, and (2) individual participatory speculative co-design sessions. Eight participants in total, with an average of over 13 years of relevant experience were involved in the study: five participated in the contextual inquiry and five in the co-design session. The concluding results from the affinity diagramming indicate that under certain conditions, therapists' retain a sense of agency in AI-supported systems for exergame-based rehabilitation, provided that their responsibility and care over their patient is not threatened. Interpreted through co-performance, this means therapists' were willing to transfer operational control to the AI while continuing to draw the boundary to retain the sense of agency, even as direct control reduced. These conditions highly depend on factors such as time, effort, level of details and level of trust. The results also suggests that AI in exergame-based rehabilitation can not substitute the roles of therapists' as subjective factors and a therapeutic alliance (TA) is essential for successful rehabilitation. Additionally, therapists' preferences for agency distribution seems to vary across the four phases of rehabilitation, where most human agency is required in the assessment & goal-setting phase, and least in the rehabilitation session and post-session evaluation phase. While the research sample is small, the participants and methods were of qualitative nature, thereby reliably contributing a phase-dependent account of how agential cut between therapists' and an AI-system is re-drawn across rehabilitation, extending the idea of co-performance into an exergame-based rehabilitation setting. We however suggest future researchers and product designers to continue to explore therapists' sense of agency through more dimensions within all four phases of therapy to accurately determine the design implications for a human-in-the-loop AI-supported computational system for exergame-based rehabilitation.





